"""empty message

Revision ID: 114b618a8d9b
Revises: 4f818e77bc84
Create Date: 2024-06-01 07:38:59.747026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114b618a8d9b'
down_revision = '4f818e77bc84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding_lost_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_found', sa.Boolean(), nullable=True))

    with op.batch_alter_table('report_lost_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_found', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_lost_item', schema=None) as batch_op:
        batch_op.drop_column('is_found')

    with op.batch_alter_table('finding_lost_items', schema=None) as batch_op:
        batch_op.drop_column('is_found')

    # ### end Alembic commands ###
